### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by ksl29** [kadeem-lewis/pokedle#3]
Allow users to access and play previous days

**Comment by kadeem-lewis** [comment]
I can store the date in the url just like I do for game mode. If there is no date param then use the current date, if there is a date then use that date

**Comment by kadeem-lewis** [comment]
I can probably have it so clicking on the calendar date redirects with that date as a param and then have a check for the date to see what to retrieve. 

There would be errors that arise due to  what is stored in localStorage in relation to the constant date swapping. I think I am currently storing the date in localStorage as well so maybe I can use that to resolve the issue
